execution:
  auto_place_trades: false
  paper_trading: true

backtest:
  start_date: "2020-01-01"
  end_date: "2023-12-31"
  symbols: ["SPY", "QQQ"]
  initial_balance: 100000
  commission: 0.00  # Per trade

strategies:
  iron_condor:
    enabled: true
    width_percent: 0.05
    min_credit: 1.00
    max_dte: 45
  
  iron_butterfly:
    enabled: true
    width_percent: 0.02
    min_credit: 0.80
    max_dte: 30
  
  trend_following:
    enabled: true
    stop_loss_pct: 0.05
    take_profit_pct: 0.10

risk:
  max_portfolio_risk: 0.05
  max_position_risk: 0.02
  daily_loss_limit: 0.10

data:
  source: "yahoo"  # yahoo or local
  offline_mode: false